{% set name = "deltalake" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: c956791c25fbb8958e89f058428d6a167dcb3bebd23889077473865f1faa1263

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - maturin >=1,<2
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
  host:
    - python
    - maturin >=1,<2
    - pip
    - xz  # [linux]
  run:
    - pyarrow-hotfix
    - python
    - pyarrow >=8

test:
  imports:
    - deltalake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: licenses/

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
