{% set name = "deltalake" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: 29881b267d1d1f180385253c093c0ae16774268c741187b149a3ec9ae15fb295

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2
    - make
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
  host:
    - python
    - maturin >=1,<2
    - pip
    - xz  # [linux]
  run:
    - pyarrow-hotfix
    - python
    - pyarrow >=8

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: licenses/

extra:
  recipe-maintainers:
    - dhirschfeld
    - charlesbluca
